In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Embedding
from google.colab import files



In [ ]:
files.upload()

Saving spam.csv to spam.csv


{'spam.csv': b'Category,Message\r\nham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."\r\nham,Ok lar... Joking wif u oni...\r\nspam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C\'s apply 08452810075over18\'s\r\nham,U dun say so early hor... U c already then say...\r\nham,"Nah I don\'t think he goes to usf, he lives around here though"\r\nspam,"FreeMsg Hey there darling it\'s been 3 week\'s now and no word back! I\'d like some fun you up for it still? Tb ok! XxX std chgs to send, \xc2\xa31.50 to rcv"\r\nham,Even my brother is not like to speak with me. They treat me like aids patent.\r\nham,As per your request \'Melle Melle (Oru Minnaminunginte Nurungu Vettam)\' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune\r\nspam,WINNER!! As a valued network customer you have been selected to receivea \xc2\xa3900

In [ ]:
spam = pd.read_csv("spam.csv")              #1º
spam.head()

In [ ]:
labelencoder = LabelEncoder()     #2º  #Instância do modelo, criando a variável label encoder e passando o parâmetro LabelEndcoder()
y = labelencoder.fit_transform(spam['Category'])
print(y)

In [ ]:
mensagens = spam['Message'].values                       #3º
X_train, X_test, y_train, y_test = train_test_split(mensagens, y, test_size=0.3)
print(X_train)

['Small problem in auction:)punj now asking tiwary'
 'Aight, sounds good. When do you want me to come down?'
 'Sleeping nt feeling well' ... "I'm vivek:)i got call from your number."
 'K tell me anything about you.'
 'You have 1 new message. Call 0207-083-6089']


In [ ]:
vetorizador = CountVectorizer()                #vetorizando o conjunto de treino.      4º
vetorizador.fit(X_train)
X_train = vetorizador.transform(X_train)
X_test = vetorizador.transform(X_test)
print(X_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
#model = Sequential()    # treinando o modelo salvando no formato JSON
#model.add(Dense(100, activation='relu', input_shape=(X_train.shape[1],)))         camada de entrada1
#model.add(Dropout(0.2))                                                           removendo neurônios ocultos da camada de entrada
#model.add(Dense(50, activation='relu'))                                           camada 2
#model.add(Dropout(0.2))                                                           camada 2 removendo neurônios ocultos
#model.add(Dense(1, activation='sigmoid'))                                         camada 3 função de ativação sigmoid
#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) camada 4 método da acurracia grau de proximidade entre os neurônios.
#model.fit(X_train, y_train, epochs=10, batch_size=32)                             tamanho rede neural
#y_pred = model.predict(X_test)                                                    camada 5 predição do model
#y_pred = (y_pred > 0.5)
#cm = confusion_matrix(y_test, y_pred)                                             medindo a integridade do treino. tp, tn relevantes.
#print(cm)
##with open("model.json", "w") as json_file:                                       salvando o treino em json. possibilidades(css,csv,html,py...)
 # json_file.write(model_json)
#model.save_weights("model.h5")
#print("Saved model to disk")

**Notes**

**Batch Size** é um termo usado em aprendizado de máquina e refere-se ao número de exemplos de treinamento usados em uma iteração.

**Bath mode** onde o tamanho do lote é igual ao conjunto de dados total, tornando os valores de iteração e épocas equivalentes.

**mini-batch mode** onde o tamanho do lote é maior do que um, mas menor que o tamanho total do conjunto de dados, um número que pode ser dividido no tamanho total do conjunto de dados.

**stochastic mode**
onde o tamanho do lote é igual a um. O gradiente e os parâmetros da rede neural são atualizados após cada amostra.

In [ ]:
X_train

<3900x7250 sparse matrix of type '<class 'numpy.int64'>'
	with 52097 stored elements in Compressed Sparse Row format>

In [ ]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y_train

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
y_test

array([1, 0, 0, ..., 1, 0, 0])

**Implementando a parte RNA**

In [ ]:
import numpy as np
np.set_printoptions(threshold=np.inf)

In [ ]:
X_train.toarray()[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
print(X_train.shape[0])

3900


In [ ]:
print(X_train.shape[1])

7250


In [ ]:
modelo = Sequential()
modelo.add(Dense(units=10,activation="relu",input_dim=X_train.shape[1]))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=8,activation="relu"))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=1,activation="sigmoid"))

**Notes**

**Propriedade**
Dropout: Minimizando overfitting. (impedindo a saturação dos neurônios nas camadas de ativação).

Algoritimo 'Adam', utilizado em RNAs profundas como optimizador da camada model.compilação, responsavel pela decida do gradiente. Substitui o atual gradiente da camada por um gradiente randomizado.
Adam combina recursos de muitos algoritimos de otimização em uma regra de atualização bastante robusta.
https://pt.d2l.ai/chapter_optimization/adam.html.

**Notes**

Um dos grandes desafios do overfitting é evitar a saturação do modelo antes do momento do teste.

**Resolução**

Podemos parar o tentativas de treino com o mesmo conjunto de teste quando a acurracia ficar abaixo de (0.70).

In [ ]:
modelo.compile(loss="mean_squared_error", optimizer="adam", metrics=["accuracy"])
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                72510     
                                                                 
 dropout (Dropout)           (None, 10)                0         
                                                                 
 dense_1 (Dense)             (None, 8)                 88        
                                                                 
 dropout_1 (Dropout)         (None, 8)                 0         
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 72607 (283.62 KB)
Trainable params: 72607 (283.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
#acurracia para validação:crossvalidation do que a acurracia a treino.
modelo.fit(X_train, y_train,epochs=20,batch_size=10, verbose=True, validation_data=(X_test, y_test))

Epoch 1/20
390/390 [==============================] - 3s 4ms/step - loss: 0.1065 - accuracy: 0.9177 - val_loss: 0.0235 - val_accuracy: 0.9779
Epoch 2/20
390/390 [==============================] - 1s 4ms/step - loss: 0.0159 - accuracy: 0.9887 - val_loss: 0.0151 - val_accuracy: 0.9821
Epoch 3/20
390/390 [==============================] - 1s 3ms/step - loss: 0.0092 - accuracy: 0.9941 - val_loss: 0.0135 - val_accuracy: 0.9844
Epoch 4/20
390/390 [==============================] - 1s 3ms/step - loss: 0.0066 - accuracy: 0.9949 - val_loss: 0.0129 - val_accuracy: 0.9850
Epoch 5/20
390/390 [==============================] - 2s 4ms/step - loss: 0.0047 - accuracy: 0.9967 - val_loss: 0.0129 - val_accuracy: 0.9850
Epoch 6/20
390/390 [==============================] - 2s 5ms/step - loss: 0.0039 - accuracy: 0.9974 - val_loss: 0.0133 - val_accuracy: 0.9850
Epoch 7/20
390/390 [==============================] - 1s 4ms/step - loss: 0.0030 - accuracy: 0.9987 - val_loss: 0.0137 - val_accuracy: 0.9844
Epoch 

In [ ]:
modelo.fit(X_train, y_train,epochs=5,batch_size=10, verbose=True, validation_data=(X_test, y_test))

Epoch 1/5
390/390 [==============================] - 1s 4ms/step - loss: 7.2431e-04 - accuracy: 0.9997 - val_loss: 0.0153 - val_accuracy: 0.9827
Epoch 2/5
390/390 [==============================] - 1s 3ms/step - loss: 6.3049e-04 - accuracy: 0.9997 - val_loss: 0.0149 - val_accuracy: 0.9844
Epoch 3/5
390/390 [==============================] - 1s 3ms/step - loss: 6.1266e-04 - accuracy: 0.9995 - val_loss: 0.0149 - val_accuracy: 0.9833
Epoch 4/5
390/390 [==============================] - 1s 3ms/step - loss: 7.7363e-04 - accuracy: 0.9995 - val_loss: 0.0148 - val_accuracy: 0.9833
Epoch 5/5
390/390 [==============================] - 1s 3ms/step - loss: 6.6092e-04 - accuracy: 0.9997 - val_loss: 0.0147 - val_accuracy: 0.9833


In [ ]:
loss, accuracy = modelo.evaluate(X_test, y_test)
print("Loss: ", loss)
print("Acurácia: ", accuracy)

53/53 [==============================] - 0s 2ms/step - loss: 0.0147 - accuracy: 0.9833
Loss:  0.014744834043085575
Acurácia:  0.9832535982131958


In [ ]:
nova_previsao = modelo.predict(X_test)
print(nova_previsao)

53/53 [==============================] - 0s 3ms/step
[[9.88115489e-01]
 [1.52235254e-04]
 [1.30316232e-06]
 [6.14829827e-04]
 [3.54081261e-12]
 [5.38447675e-05]
 [1.92140666e-04]
 [5.47468835e-06]
 [2.81085868e-05]
 [1.00699463e-05]
 [4.48128557e-12]
 [1.00000000e+00]
 [1.00000000e+00]
 [1.15950813e-03]
 [9.99994338e-01]
 [8.47820193e-04]
 [2.24066071e-06]
 [3.43946012e-05]
 [5.23200194e-09]
 [9.02660177e-05]
 [9.99984980e-01]
 [8.57069826e-05]
 [2.66376929e-07]
 [1.77069509e-04]
 [8.25039693e-04]
 [2.44609728e-05]
 [5.68616940e-07]
 [6.49506035e-07]
 [1.10743823e-03]
 [4.59035109e-05]
 [1.00000000e+00]
 [3.45712993e-04]
 [3.37859266e-04]
 [9.45510983e-04]
 [3.77470855e-08]
 [2.54113486e-09]
 [4.93545249e-09]
 [4.98159807e-08]
 [3.10300749e-07]
 [9.98761475e-01]
 [2.14876703e-08]
 [1.27491518e-03]
 [2.52911121e-07]
 [3.38811674e-06]
 [4.80232900e-03]
 [9.45510983e-04]
 [1.24012376e-03]
 [7.82679854e-05]
 [1.60965836e-04]
 [7.20964791e-03]
 [4.56832859e-05]
 [2.45501491e-04]
 [5.8420428

In [ ]:
prev = (nova_previsao > 0.5)
print(prev)

[[ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 

**Embeddings**

Podemos criar um vetor esparso de 0 e 1s (fizemos anteriormente) ou



*   Vetor denso fixo com pesos da relação entre as palavras
     * Usar um embedding
     * Treinar nosso próprio

* Keras possui um tipo de camada Embedding


**Embedding**

  * input_dim: Tamanho do vocabulário
  * output_dim: Tamanho do vetor denso
  * input_length: Tamanho máximo da sequência
  * Camada Embedding deve ser conectada a uma camada Flatten
  * Camada Flatten concetada a uma Densa
  *Etc....


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Embedding
from google.colab import files

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [ ]:
files.upload()

Saving spam.csv to spam (1).csv


{'spam (1).csv': b'Category,Message\r\nham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."\r\nham,Ok lar... Joking wif u oni...\r\nspam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C\'s apply 08452810075over18\'s\r\nham,U dun say so early hor... U c already then say...\r\nham,"Nah I don\'t think he goes to usf, he lives around here though"\r\nspam,"FreeMsg Hey there darling it\'s been 3 week\'s now and no word back! I\'d like some fun you up for it still? Tb ok! XxX std chgs to send, \xc2\xa31.50 to rcv"\r\nham,Even my brother is not like to speak with me. They treat me like aids patent.\r\nham,As per your request \'Melle Melle (Oru Minnaminunginte Nurungu Vettam)\' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune\r\nspam,WINNER!! As a valued network customer you have been selected to receivea \xc2\xa

In [ ]:
spam = pd.read_csv("spam.csv")
spam.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [ ]:
labelencoder = LabelEncoder()    #hot encode dos dados, transformando dados (words) dados em númericos.
y = labelencoder.fit_transform(spam['Category'])
print(y)

[0 0 1 0 0 1 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 1 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 0 1 

In [ ]:
mensagem = spam['Message'].values
X_train, X_test, y_train, y_test = train_test_split(mensagem, y, test_size=0.3)
print(X_train)

['Wa... U so efficient... Gee... Thanx...'
 'Nan sonathaya soladha. Why boss?'
 'I met you as a stranger and choose you as my friend. As long as the world stands, our friendship never ends. Lets be Friends forever!!! Gud nitz...'
 "Uh, heads up we don't have THAT much left"
 'I had been hoping i would not have to send you this message. My rent is due and i dont have enough for it. My reserves are completely gone. Its a loan i need and was hoping you could her. The balance is  &lt;#&gt; . Is there a way i could get that from you, till mid march when i hope to pay back.'
 'Captain vijaykanth is doing comedy in captain tv..he is drunken :)'
 'Only saturday and sunday holiday so its very difficult:)'
 'Hmm .. Bits and pieces lol ... *sighs* ...'
 'Oh thats late! Well have a good night and i will give u a call tomorrow. Iam now going to go to sleep night night'
 'Happy new year to u and ur family...may this new year bring happiness , stability and tranquility to ur vibrant colourful life:):

In [ ]:
token = Tokenizer(num_words=1000)
token.fit_on_texts(X_train)

X_train = token.texts_to_sequences(X_train)
X_test = token.texts_to_sequences(X_test)

In [ ]:
display([X_train])

[[[6, 25, 413],
  [172],
  [1,
   3,
   75,
   4,
   7,
   616,
   3,
   75,
   11,
   288,
   75,
   317,
   75,
   5,
   347,
   94,
   494,
   318,
   852,
   688,
   27,
   268,
   853,
   209],
  [42, 39, 96, 17, 20, 121, 465],
  [1,
   138,
   104,
   1,
   177,
   23,
   17,
   2,
   65,
   3,
   41,
   151,
   11,
   9,
   7,
   1,
   95,
   17,
   428,
   12,
   15,
   11,
   22,
   924,
   617,
   66,
   4,
   1,
   72,
   7,
   62,
   3,
   210,
   105,
   5,
   787,
   9,
   52,
   50,
   9,
   67,
   4,
   125,
   1,
   210,
   30,
   20,
   46,
   3,
   466,
   854,
   43,
   1,
   132,
   2,
   467,
   97],
  [9, 153, 8, 377, 69, 9],
  [63, 925, 7, 788, 255, 25, 66, 164],
  [689, 7, 178],
  [122,
   319,
   215,
   123,
   17,
   4,
   59,
   127,
   7,
   1,
   28,
   154,
   6,
   4,
   16,
   159,
   19,
   80,
   2,
   48,
   2,
   206,
   127,
   127],
  [139,
   100,
   275,
   2,
   6,
   7,
   33,
   618,
   245,
   41,
   100,
   275,
   513,
   789,
   7,
   2,

In [ ]:
#X_train = pad_sequences()

In [ ]:
print(len(X_train))     #(0.30)
print(len(y_test))

3900
1672


In [ ]:
import numpy as np
np.set_printoptions(threshold=np.inf)

In [ ]:
import numpy as np

In [ ]:
#X_train.toarray()[0]

In [ ]:
display(X_train)

[[6, 25, 413],
 [172],
 [1,
  3,
  75,
  4,
  7,
  616,
  3,
  75,
  11,
  288,
  75,
  317,
  75,
  5,
  347,
  94,
  494,
  318,
  852,
  688,
  27,
  268,
  853,
  209],
 [42, 39, 96, 17, 20, 121, 465],
 [1,
  138,
  104,
  1,
  177,
  23,
  17,
  2,
  65,
  3,
  41,
  151,
  11,
  9,
  7,
  1,
  95,
  17,
  428,
  12,
  15,
  11,
  22,
  924,
  617,
  66,
  4,
  1,
  72,
  7,
  62,
  3,
  210,
  105,
  5,
  787,
  9,
  52,
  50,
  9,
  67,
  4,
  125,
  1,
  210,
  30,
  20,
  46,
  3,
  466,
  854,
  43,
  1,
  132,
  2,
  467,
  97],
 [9, 153, 8, 377, 69, 9],
 [63, 925, 7, 788, 255, 25, 66, 164],
 [689, 7, 178],
 [122,
  319,
  215,
  123,
  17,
  4,
  59,
  127,
  7,
  1,
  28,
  154,
  6,
  4,
  16,
  159,
  19,
  80,
  2,
  48,
  2,
  206,
  127,
  127],
 [139, 100, 275, 2, 6, 7, 33, 618, 245, 41, 100, 275, 513, 789, 7, 2, 33, 155],
 [216, 2, 467, 25, 1, 138, 2, 48, 2, 5, 855, 2, 5],
 [9, 44],
 [1, 62, 20, 68, 3, 67],
 [211, 39, 72, 112, 7, 2, 12, 31, 1, 389, 3, 229, 1, 72, 13

In [ ]:
X_train = pad_sequences(X_train, padding="post", maxlen=500)
X_test = pad_sequences(X_test, padding="post", maxlen=500)

In [ ]:
#X_train.toarray()

In [ ]:
print(X_train.shape[1])

500


In [ ]:
modelo = Sequential()
modelo.add(Dense(units=10,activation="relu",input_dim=X_train.shape[1]))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=8,activation="relu"))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=1,activation="sigmoid"))
modelo.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 10)                5010      
                                                                 
 dropout_2 (Dropout)         (None, 10)                0         
                                                                 
 dense_4 (Dense)             (None, 8)                 88        
                                                                 
 dropout_3 (Dropout)         (None, 8)                 0         
                                                                 
 dense_5 (Dense)             (None, 1)                 9         
                                                                 
Total params: 5107 (19.95 KB)
Trainable params: 5107 (19.95 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


**RNA 2**

In [ ]:
modelo = Sequential()
modelo.add(Embedding(input_dim=len(token.word_index), output_dim=50,input_length=500))
modelo.add(Flatten())

modelo.add(Dense(units=10,activation="relu"))
modelo.add(Dropout(0.1))
modelo.add(Dense(units=1,activation="sigmoid"))


In [ ]:
modelo.compile(loss="mean_squared_error", optimizer="adam",metrics=["accuracy"])
modelo.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 500, 50)           373800    
                                                                 
 flatten (Flatten)           (None, 25000)             0         
                                                                 
 dense_6 (Dense)             (None, 10)                250010    
                                                                 
 dropout_4 (Dropout)         (None, 10)                0         
                                                                 
 dense_7 (Dense)             (None, 1)                 11        
                                                                 
Total params: 623821 (2.38 MB)
Trainable params: 623821 (2.38 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
modelo.fit(X_train, y_train, epochs=5, batch_size=10, verbose=True, validation_data=(X_test, y_test))

Epoch 1/5
390/390 [==============================] - 7s 15ms/step - loss: 0.0750 - accuracy: 0.9162 - val_loss: 0.0401 - val_accuracy: 0.9683
Epoch 2/5
390/390 [==============================] - 4s 10ms/step - loss: 0.0357 - accuracy: 0.9823 - val_loss: 0.0315 - val_accuracy: 0.9785
Epoch 3/5
390/390 [==============================] - 4s 9ms/step - loss: 0.0258 - accuracy: 0.9910 - val_loss: 0.0251 - val_accuracy: 0.9839
Epoch 4/5
390/390 [==============================] - 5s 14ms/step - loss: 0.0192 - accuracy: 0.9933 - val_loss: 0.0232 - val_accuracy: 0.9839
Epoch 5/5
390/390 [==============================] - 4s 10ms/step - loss: 0.0149 - accuracy: 0.9956 - val_loss: 0.0199 - val_accuracy: 0.9844


In [ ]:
loss, accuracy = modelo.evaluate(X_test,y_test)
print("Loss: ", loss)
print("Acurácia: ", accuracy)

53/53 [==============================] - 0s 4ms/step - loss: 0.0199 - accuracy: 0.9844
Loss:  0.019936641678214073
Acurácia:  0.9844497442245483
